### ISSUE TITLE
Add ability to configure context-path for management center

### ISSUE THREAD

**Issue by nstuart-idexx** [hazelcast/hazelcast-platform-operator#933]
**Operator Version**: 5.10

We have a requirement to serve the management center under a different (non-root) context path. 

Currently, you can configure this value via the jvm.args properties in the resource, but the deployment fails because the readiness probe fails because it points the the root `/health`, instead of whatever the property is configured against.

**Comment by cagric0** [comment]
Thanks for the issue and the feedback.
We've created the necessary issue internally and we will start to work on it ASAP. I'll keep up to date this issue related to our progress.

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-platform-operator/pull/989
